spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/devsurfer
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: e460dc5cbc6d915e4e3b
            client-secret: e62e86b797da82056b1c69170db7bb6165c7c828